name: Deploy to Main

on:
  push:
    branches:
      - main  # Triggers deployment when ANYONE pushes to staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRODUCTION_EC2_PRODUCTION_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-3-149-213-181.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy via Rsync
        run: |
          cd ./src/frontend/aigentqube-dashboard/
          rsync -avz --exclude 'node_modules' --exclude '.git' --exclude '.env' \
          -e "ssh -i ~/.ssh/iQube_production_keyPair.pem" \
          . ubuntu@ec2-3-149-213-181.us-east-2.compute.amazonaws.com:~/app
          ssh ubuntu@ec2-3-149-213-181.us-east-2.compute.amazonaws.com << 'EOF'
            cd ~/app
            npm install
            cd ~
            sudo systemctl restart myapp.service
          EOF
